backend/modules/price_book/models/PriceBook.php
<?php

namespace backend\modules\price_book\models;

use backend\modules\product\models\Item;
use yii;
use common\models\price_book\PriceBook as BasePriceBook;

use yii\helpers\ArrayHelper;


class PriceBook extends BasePriceBook
{
    public $product_articul;
    public $product_title;

    public static function saveXml()
    {
        $sql = 'SELECT pb.id,pb.product_id, pi.articul AS product_articul, pi.title AS product_title,  pb.price, pb.group_id
                FROM price_book pb
                INNER JOIN product_item pi
                ON(pi.id = pb.product_id)';
        $price_book = PriceBook::findBySql($sql)->all();
        $res = self::modelsToXml($price_book, 'price_book', "product");
        return $res;
    }

    private static function modelsToXml($models, $rootElementName, $childElementName)
    {
        $atributeType = [];
        $model = new PriceBook();
        $atributes = self::attributes();
        foreach ($atributes as $key=>$value){
            $atributeType[$value] = $model->getTableSchema()->getColumn($value)->phpType;
        }
        $xmlData = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
        $xmlData .= "\t<" . $rootElementName . ">\n";
        foreach ($models as $model) {
            $xmlData .= "\t\t<" . $childElementName . ">\n";
            foreach($model as $key=>$value){
                $xmlData .= "\t\t\t<column type=\"".$atributeType[$key] ."\" name=\"" . $key . "\">";
                if(!empty($value)){
                    $xmlData .=  $value;
                } else{
                    $xmlData .= "null";
                }
                $xmlData .= "</column>\n";
            }
            $xmlData .= "\t\t\t<column type=\"string\" name=\"product_articul\">". $model->product_articul ."</column>\n";
            $xmlData .= "\t\t\t<column type=\"string\" name=\"product_title\">". $model->product_title ."</column>\n";
            $xmlData .= "\t\t</" . $childElementName . ">\n";
        }
        $xmlData .= "\t</" . $rootElementName . ">\n";
        return $xmlData;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroup()
    {
        return $this->hasOne(GroupName::className(), ['id' => 'group_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(Item::className(), ['id' => 'product_id']);
    }
 }

backend/modules/price_book/controllers/PriceBookController.php
<?php

namespace backend\modules\price_book\controllers;

use backend\modules\core\models\ImportXml;
use yii\base\Exception;
use yii;
use backend\modules\price_book\models\PriceBook;
use backend\modules\price_book\models\PriceBookSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * PriceBookController implements the CRUD actions for PriceBook model.
 */
class PriceBookController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PriceBook models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PriceBookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PriceBook model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PriceBook model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new PriceBook();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing PriceBook model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing PriceBook model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PriceBook model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PriceBook the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PriceBook::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Export PriceBook model from DB to XML.
     * @return Save price_book.xml file
     */
    public function actionExportXml(){
        $xml = PriceBook::saveXml();
        $response = Yii::$app->response;
        $response->format = \yii\web\Response::FORMAT_XML;
        $response->sendContentAsFile($xml, 'price_book.xml')->send();
    }

    /**
     * Import from XML to PriceBook table.
     * @return Flash message to index page
     * Redirect to index page
     */
    public function actionImportXml(){
        $model = new ImportXml();
        if (Yii::$app->request->isPost) {
            $model->file = UploadedFile::getInstanceByName('importFile');
            $errors = [];
            $updateCount =0;
            $newCount =0;
            $errorCount = 0;
            if ($model->validate() && $models =$model->upload()) {
                $priceBooks = ArrayHelper::index(PriceBook::find()->all(), 'id');
                $priceBook = new PriceBook();
                foreach ($models as $key => $value) {
                    try {
                        if (array_key_exists($value['id'], $priceBooks)) { //обновление
                            $priceBook = $priceBooks[$value['id']];
                            $priceBook->attributes=$value;
                            if($priceBook->validate()){
                                $priceBook->save(false);
                                $updateCount++;
                            } else{
                                $errorCount++;
                                $str="При обновлении id= $priceBook->id<br>";
                                foreach ($priceBook->errors as $key=>$value){
                                    foreach ($value as $k=>$val){
                                        $str .="$key: $val <br>";
                                    }
                                }
                                $errors[] = $str;
                            }
                        } else {                                        //добавление нового
                            $priceBook->attributes=$value;
                            $priceBook->id = $value['id'];
                            if($priceBook->validate()){
                                $priceBook->isNewRecord = true;
                                $priceBook->save(false);
                                $newCount++;
                            }
                            else{
                                $errorCount++;
                                $str="При добавлении записи ID: $priceBook->id<br>";
                                foreach ($priceBook->errors as $key=>$value){
                                    foreach ($value as $k=>$val){
                                        $str .="$key: $val <br>";
                                    }
                                }
                                $errors[] = $str;
                            }
                        }
                    } catch (Exception $ex) {
                        $errorCount++;
                        $message = $ex->errorInfo[2];
                        $errors[] = "Ошибка при сохранении: $message";
                    }
                }
            }
            else{
                $errorCount++;
                $errors[] = "Ошибка загрузки файла"; //ошибка загрузки файла
            }
        }
        $errorStr = '';
        foreach ($errors as $value){
            $errorStr .= "<p>$value</p>";
        }
        Yii::$app->session->setFlash('load', "Загружено $newCount товаров.<br> Обновлено $updateCount товаров. <br> Ошибок {$errorCount}.<br> $errorStr");
        $this->redirect(['/price_book/price-book/index'], 301);
    }

}

backend/modules/price_book/views/price-book/_form.php
<?php


use backend\modules\price_book\models\GroupName;
use backend\modules\product\models\Item;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model backend\modules\price_book\models\PriceBook */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="price-book-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php
    $form->field($model, 'product_id')->widget(Select2::classname(), [
        'data' => ArrayHelper::map(Item::find()->all(), 'id', 'articul'),
        'options' => ['placeholder' => 'Выберите продукт'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]);
    ?>

    <?= $form->field($model, 'product_id')->dropDownList(ArrayHelper::map(Item::find()->all(), 'id', 'articul') ) ?>

    <?= $form->field($model, 'price')->textInput(['maxlength' => true]) ?>

    <?=$form->field($model, 'group_id')->dropDownList(ArrayHelper::map(GroupName::find()->all(), 'id', 'name'), ['prompt' => 'Выберите группу']);?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/price_book/views/price-book/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\price_book\models\PriceBookSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="price-book-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'product_id') ?>

    <?= $form->field($model, 'price') ?>

    <?= $form->field($model, 'group_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/modules/price_book/views/price-book/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\modules\price_book\models\PriceBook */

$this->title = 'Create Price Book';
$this->params['breadcrumbs'][] = ['label' => 'Price Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="price-book-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/price_book/views/price-book/index.php
<?php

use backend\modules\price_book\models\GroupName;
use backend\modules\price_book\models\GroupType;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\price_book\models\PriceBookSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Price Book';
$this->params['breadcrumbs'][] = $this->title;

$groups = [];
$type = GroupType::find()->all();
foreach ($type as $value){
    $groups[$value->name] = ArrayHelper::map(GroupName::find()->where(['type'=> $value->id])->all(), 'id', 'name');
}



?>
<div class="price-book-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <?php
    if(Yii::$app->session->hasFlash('load')):?>
        <div class="alert alert-danger">
            <?php echo Yii::$app->session->getFlash('load'); ?>
        </div>
    <?php endif; ?>
    <p>
        <?= Html::a('Create Price Book', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'product_id',
            [
                'attribute' => 'product.title',
            ],
            [
                'attribute' => 'product.articul',
            ],
            'price',
            [
                'attribute' => 'group.name',
                'filter' => Html::activeDropDownList($searchModel, 'group_id', $groups, ['class' => 'form-control', 'prompt' => 'Выберите группу']),
            ],
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>
<a href="<?= Url::toRoute(['price-book/export-xml'])?>" class="btn btn-success" id="price_book">Экспорт price book в XML</a>

<?= Html::beginForm(['price-book/import-xml'], 'post', ['enctype' => 'multipart/form-data', 'id'=>'import']) ?>

<div class=" btn btn-success file-upload">
    <label>
        <?= Html::fileInput('importFile','', ['id'=>'importFlie']) ?>
        <span>Импорт price book из XML</span>
    </label>
</div>
<?= Html::endForm() ?>

<?php
$this->registerJs("
        $('#importFlie').on('change', function(event){
             $('#import').submit();
        }); 
        setTimeout(function() { $('.alert').hide('slow'); }, 10000);
        ");

?>

backend/modules/price_book/views/price-book/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\price_book\models\PriceBook */

$this->title = 'Update Price Book: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Price Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="price-book-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/modules/price_book/views/price-book/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\modules\price_book\models\PriceBook */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Price Books', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="price-book-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'product_id',
            'price',
            'group_id',
        ],
    ]) ?>

</div>